### ISSUE TITLE
Full width image field

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#237]
### Steps to reproduce the issue
The image field is now full width which makes no sense and bizarrely results in a smaller image

### Joomla 4 
![image](https://user-images.githubusercontent.com/1296369/58372810-02d70000-7f1b-11e9-9a3b-73d14061eeac.png)

### This template repo
![image](https://user-images.githubusercontent.com/1296369/58372807-f94d9800-7f1a-11e9-9b7c-50089eb31fd4.png)

**Comment by bembelimen** [comment]
Should be resolved with: https://github.com/joomla/backend-template/pull/252

Thx.

**Comment by brianteeman** [comment]
No the changes there doesnt resolve this
![image](https://user-images.githubusercontent.com/1296369/60706790-26ba3800-9f02-11e9-967a-7452fee85de0.png)

**Comment by brianteeman** [comment]
Although I guess it doesnt look as bad with the label being moved
